[profile.default]
src = "src"
out = "out"
libs = [
    "lib",
    "node_modules",
]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "hardhat/=node_modules/hardhat/",
]

[rpc_endpoints]
arc_testnet = "${ARC_TESTNET_RPC_URL}"
arc = "${ARC_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
